In [13]:
from google.colab import drive
import os

drive.mount('/content/drive')

caminho = '/content/drive/MyDrive/Aula_llm/Trabalho final/Dados/IBM'

caminho_accounts = '/content/drive/MyDrive/Aula_llm/Trabalho final/Dados/IBM/LI-Small_accounts.csv'
caminho_trans = '/content/drive/MyDrive/Aula_llm/Trabalho final/Dados/IBM/LI-Small_Trans.csv'

print(os.path.exists(caminho_accounts))
print(os.path.exists(caminho_trans))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
True
True

In [15]:
len(df_trans), len(df_accounts)

(6924049, 712688)

In [16]:
sum(df_trans['Is Laundering'] == 1)

3565

In [12]:
import pandas as pd

df_trans = pd.read_csv(caminho_trans)

In [ ]:
colunms_trans = df_trans.columns

In [ ]:
colunms_trans

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='object')

In [ ]:
df_resultado = df_trans.copy()
df_resultado.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3195403.00,US Dollar,3195403.00,US Dollar,Reinvestment,0
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1858.96,US Dollar,1858.96,US Dollar,Reinvestment,0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,592571.00,US Dollar,592571.00,US Dollar,Cheque,0
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,12.32,US Dollar,12.32,US Dollar,Reinvestment,0
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2941.56,US Dollar,2941.56,US Dollar,Reinvestment,0

In [ ]:
print(df_resultado.shape)

memoria_gb = df_resultado.memory_usage(deep=True).sum() / 1024**3
print(f"Memória usada: {memoria_gb:.2f} GB")

print(df_resultado["Is Laundering"].value_counts())

(6924049, 11)
Memória usada: 2.52 GB
Is Laundering
0    6920484
1       3565
Name: count, dtype: int64

In [ ]:
df_resultado.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

TARGET = "Is Laundering"


def criar_variaveis_ibm_para_grafo(df):
    df = df.copy()
    df.columns = df.columns.str.strip()

    # =========================
    # 1. Data
    # =========================
    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")

    ts = df["Timestamp"]

    df["ano"] = ts.dt.year
    df["mes"] = ts.dt.month
    df["dia_mes"] = ts.dt.day
    df["hora"] = ts.dt.hour
    df["minuto"] = ts.dt.minute
    df["dia_semana"] = ts.dt.dayofweek
    df["semana_ano"] = ts.dt.isocalendar().week.astype("float64")
    df["semana_mes"] = ((ts.dt.day - 1) // 7 + 1).astype("float64")

    df["fim_de_semana"] = df["dia_semana"].isin([5, 6]).astype(int)

    df["tipo_semana"] = np.where(
        df["fim_de_semana"] == 1,
        "fim_de_semana",
        "meio_de_semana"
    )

    h = df["hora"]

    df["periodo_dia"] = np.select(
        [
            h.between(0, 5),
            h.between(6, 11),
            h.between(12, 17),
            h.between(18, 23)
        ],
        [
            "madrugada",
            "manha",
            "tarde",
            "noite"
        ],
        default="desconhecido"
    )

    df["periodo_dia_3"] = np.select(
        [
            h.between(6, 11),
            h.between(12, 17)
        ],
        [
            "manha",
            "tarde"
        ],
        default="noite"
    )

    df["inicio_mes"] = ts.dt.is_month_start.astype("float64")
    df["fim_mes"] = ts.dt.is_month_end.astype("float64")

    # Representação cíclica
    df["hora_sin"] = np.sin(2 * np.pi * df["hora"] / 24)
    df["hora_cos"] = np.cos(2 * np.pi * df["hora"] / 24)

    df["dia_semana_sin"] = np.sin(2 * np.pi * df["dia_semana"] / 7)
    df["dia_semana_cos"] = np.cos(2 * np.pi * df["dia_semana"] / 7)

    df["mes_sin"] = np.sin(2 * np.pi * df["mes"] / 12)
    df["mes_cos"] = np.cos(2 * np.pi * df["mes"] / 12)

    # =========================
    # 2. Valores monetários
    # =========================
    df["Amount Received"] = pd.to_numeric(df["Amount Received"], errors="coerce")
    df["Amount Paid"] = pd.to_numeric(df["Amount Paid"], errors="coerce")

    df["dif_valor"] = df["Amount Paid"] - df["Amount Received"]
    df["dif_valor_abs"] = df["dif_valor"].abs()

    df["razao_pago_recebido"] = (
        df["Amount Paid"] / (df["Amount Received"] + 1e-6)
    )

    df["amount_paid_log"] = np.log1p(df["Amount Paid"].clip(lower=0))
    df["amount_received_log"] = np.log1p(df["Amount Received"].clip(lower=0))

    # =========================
    # 3. Relações origem-destino
    # =========================
    df["mesmo_banco"] = (
        df["From Bank"].astype(str) == df["To Bank"].astype(str)
    ).astype(int)

    df["mesma_conta"] = (
        df["Account"].astype(str) == df["Account.1"].astype(str)
    ).astype(int)

    df["mesma_moeda"] = (
        df["Payment Currency"].astype(str) == df["Receiving Currency"].astype(str)
    ).astype(int)

    df["pagamento_reinvestment"] = (
        df["Payment Format"].astype(str).str.lower() == "reinvestment"
    ).astype(int)

    # =========================
    # 4. IDs para grafo
    # =========================
    df["source_account_id"] = (
        df["From Bank"].astype(str).str.strip()
        + "_"
        + df["Account"].astype(str).str.strip()
    )

    df["target_account_id"] = (
        df["To Bank"].astype(str).str.strip()
        + "_"
        + df["Account.1"].astype(str).str.strip()
    )

    # ID único da transação
    df["transaction_id"] = np.arange(len(df))

    return df

In [ ]:
import gc
TARGET = "Is Laundering"

df_resultado[TARGET] = df_resultado[TARGET].astype("int8")

df_fraudes = df_resultado[df_resultado[TARGET] == 1]
df_normais = df_resultado[df_resultado[TARGET] == 0]

print("Fraudes:", len(df_fraudes))
print("Normais:", len(df_normais))

proporcao_normais = 10

qtd_normais = min(
    len(df_normais),
    len(df_fraudes) * proporcao_normais,
    100_000
)

df_normais_amostra = df_normais.sample(
    n=qtd_normais,
    random_state=42
)

df_grafo = pd.concat(
    [df_fraudes, df_normais_amostra],
    axis=0
).sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print(df_grafo.shape)
print(df_grafo[TARGET].value_counts())

del df_fraudes
del df_normais
del df_normais_amostra
gc.collect()

Fraudes: 3565
Normais: 6920484
(39215, 11)
Is Laundering
0    35650
1     3565
Name: count, dtype: int64

27702

In [ ]:
df_resultado['Is Laundering'].value_counts()

Is Laundering
0    6920484
1       3565
Name: count, dtype: int64

In [ ]:
proporcao_normais = 10

qtd_normais = min(
    len(df_normais),
    len(df_fraudes) * proporcao_normais,
    100_000
)

df_normais_amostra = df_normais.sample(
    n=qtd_normais,
    random_state=42
)

df_grafo = pd.concat([df_fraudes, df_normais_amostra], axis=0)

df_grafo = df_grafo.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print(df_grafo.shape)
print(df_grafo[TARGET].value_counts())

(39215, 11)
Is Laundering
0    35650
1     3565
Name: count, dtype: int64

In [ ]:
import os
import pandas as pd
import numpy as np

TARGET = "Is Laundering"

caminho = "/content/drive/MyDrive/Aula_llm/Trabalho final/Dados/IBM/"
os.makedirs(caminho, exist_ok=True)

In [ ]:
df_grafo_tratado = criar_variaveis_ibm_para_grafo(df_grafo)

print(df_grafo_tratado.head())
print(df_grafo_tratado.shape)

print(df_grafo_tratado[[
    "source_account_id",
    "target_account_id",
    "Account",
    "Account.1",
    "Is Laundering"
]].head())

            Timestamp  From Bank    Account  To Bank  Account.1  \
0 2022-09-10 15:48:00      14172  8025B5F50    22693  80A9F7D70
1 2022-09-02 02:34:00         70  10042B660   237246  8172A5260
2 2022-09-07 10:46:00        498  800DAA850    21876  801C37770
3 2022-09-09 10:04:00         70  10042B660    62871  8197FBD50
4 2022-09-09 14:18:00      25304  8075B8250    24070  80CDA2C00

   Amount Received Receiving Currency  Amount Paid Payment Currency  \
0             9.56               Euro         9.56             Euro
1        152800.97          US Dollar    152800.97        US Dollar
2           144.20               Euro       144.20             Euro
3          1028.05          US Dollar      1028.05        US Dollar
4        181930.18               Euro    181930.18             Euro

  Payment Format  ...  razao_pago_recebido  amount_paid_log  \
0         Cheque  ...                  1.0         2.357073
1         Cheque  ...                  1.0        11.936898
2    Credit Card  ...                  1.0         4.978112
3         Cheque  ...                  1.0         6.936391
4           Cash  ...                  1.0        12.111384

   amount_received_log  mesmo_banco  mesma_conta  mesma_moeda  \
0             2.357073            0            0            1
1            11.936898            0            0            1
2             4.978112            0            0            1
3             6.936391            0            0            1
4            12.111384            0            0            1

   pagamento_reinvestment  source_account_id  target_account_id  \
0                       0    14172_8025B5F50    22693_80A9F7D70
1                       0       70_10042B660   237246_8172A5260
2                       0      498_800DAA850    21876_801C37770
3                       0       70_10042B660    62871_8197FBD50
4                       0    25304_8075B8250    24070_80CDA2C00

   transaction_id
0               0
1               1
2               2
3               3
4               4

[5 rows x 43 columns]
(39215, 43)
  source_account_id target_account_id    Account  Account.1  Is Laundering
0   14172_8025B5F50   22693_80A9F7D70  8025B5F50  80A9F7D70              0
1      70_10042B660  237246_8172A5260  10042B660  8172A5260              0
2     498_800DAA850   21876_801C37770  800DAA850  801C37770              0
3      70_10042B660   62871_8197FBD50  10042B660  8197FBD50              0
4   25304_8075B8250   24070_80CDA2C00  8075B8250  80CDA2C00              0

In [ ]:
y = df_grafo_tratado[TARGET].astype(int)

df_train, df_temp = train_test_split(
    df_grafo_tratado,
    test_size=0.30,
    random_state=42,
    stratify=y
)

df_val, df_test = train_test_split(
    df_temp,
    test_size=0.50,
    random_state=42,
    stratify=df_temp[TARGET]
)

print("Treino:")
print(df_train[TARGET].value_counts())

print("\nValidação:")
print(df_val[TARGET].value_counts())

print("\nTeste:")
print(df_test[TARGET].value_counts())

Treino:
Is Laundering
0    24955
1     2495
Name: count, dtype: int64

Validação:
Is Laundering
0    5347
1     535
Name: count, dtype: int64

Teste:
Is Laundering
0    5348
1     535
Name: count, dtype: int64

Arquivos para grafo salvos com sucesso!

In [ ]:
import os
import pandas as pd

TARGET = "Is Laundering"

caminho = "/content/drive/MyDrive/Aula_llm/Trabalho final/Dados/IBM/"
os.makedirs(caminho, exist_ok=True)

df_train.to_csv(
    caminho + 'dados_trans_treino.csv',
    index=False
)

df_val.to_csv(
    caminho + 'dados_trans_validacao.csv',
    index=False
)

df_test.to_csv(
    caminho + 'dados_trans_teste.csv',
    index=False
)


print("Arquivos salvos com sucesso!")

Arquivos salvos com sucesso!

# Contas de clientes

In [5]:
import pandas as pd
df_accounts = pd.read_csv(caminho_accounts)
df_accounts

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,China Bank #2820,314693,81B86A280,800D8CCF0,Corporation #41344
1,France Bank #4585,311253,8187FEA80,800B505E0,Corporation #54497
2,China Bank #2242,39996,803961E00,800D03F60,Partnership #36904
3,National Bank of Newport,331440,81B075800,801567C10,Corporation #16224
4,UK Bank #33,135417,80CF87C80,801085E00,Partnership #72930
...,...,...,...,...,...
712683,China Bank #42,692,80346A5F0,800D080A0,Corporation #40025
712684,First Bank of Watertown,118699,80B802A70,8005319C0,Partnership #14803
712685,Bank of Lincoln,213123,80847BE70,800453480,Partnership #11893
712686,Hilltop Credit Union,18747,803A36270,8003B5120,Partnership #6726
712687,Savings Bank of Helena,25242,80B66B2F0,8003122E0,Corporation #15281

In [7]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

df_accounts['Bank Type'] = df_accounts['Bank Name'].str.split('#').str[0].str.strip()
df_accounts['Entity Type'] = df_accounts['Entity Name'].str.split('#').str[0].str.strip()

# 3. Codificando as variáveis categóricas (Texto -> Número)
le_bank_type = LabelEncoder()
le_entity_type = LabelEncoder()
le_entity_id = LabelEncoder()

df_accounts['Bank Type_Encoded'] = le_bank_type.fit_transform(df_accounts['Bank Type'])
df_accounts['Entity Type_Encoded'] = le_entity_type.fit_transform(df_accounts['Entity Type'])
df_accounts['Entity ID_Encoded'] = le_entity_id.fit_transform(df_accounts['Entity ID'])

# 4. Mantendo e Normalizando o Bank ID
scaler = StandardScaler()
# O Bank ID permanece aqui, mas escalonado para a GNN performar melhor
df_accounts['Bank ID_Scaled'] = scaler.fit_transform(df_accounts[['Bank ID']])

# 5. Definindo o ID do Nó (Mapeamento de Account Number para índices 0, 1, 2...)
# GNNs exigem que os nós sejam indexados de 0 a N-1
le_account = LabelEncoder()
df_accounts['node_id'] = le_account.fit_transform(df_accounts['Account Number'])

node_features = df_accounts[['node_id', 'Account Number', 'Bank ID_Scaled', 'Bank Type_Encoded', 'Entity ID_Encoded', 'Entity Type_Encoded']]

print("Tabela Pronta para a GNN:")
print(node_features.to_string(index=False))

A saída de streaming foi truncada nas últimas 5000 linhas.
  604460      817F12290        0.310287                396             210282                    0
  145777      805B9B310       -0.960625                371             209246                    0
  451829      811D27A90       -0.052742                218              85602                    2
  292053      80B7D8190       -0.065274                328             158357                    2
  686229      81B1D6191        1.984563                124              70894                    2
  603714      817E9BA90       -0.472570                396             210106                    3
  303650      80BF10890       -0.729975                174             170247                    0
  376773      80ED78810       -0.788942                266             160997                    0
  505977      813FDA290        0.226931                218             128774                    3
   56468      80239E610       -0.863752                269             109932                    0
  379887      80EF7EE90       -0.790427                179             218275                    2
  373371      80EB46B90       -0.743714                306             220607                    0
  106467      8042D0B90       -0.908901                321             197683                    0
  249805      809CE6090        0.809436                266             167878                    2
  504196      813EAD010        0.693797                113             147442                    3
   92966      803A7F590       -0.985935                113             136680                    3
  513384      81449F210       -0.603838                462             133294                    2
  285750      80B3E1690       -0.848242                218             109626                    3
  620077      8188EB410       -0.850760                218             108448                    2
  527883      814E02390        0.021608                427              63373                    2
  194704      807A2B410        0.759427                202              55870                    0
  171333      806B92710       -0.860687                 30              32697                    0
  220914      808ADDB90       -0.879675                314              23601                    0
   19982      800CCD110       -0.810654                398              16417                    3
   87622      8037315A0       -0.738409                404             215249                    0
  605133      817F80E20       -0.465653                396             211242                    0
  442678      811747520        1.565553                269             118715                    0
  624102      818B77F20       -0.691053                184              83322                    2
  541735      8156DDEA0       -0.716982                218             109150                    3
  114773      8047F54A0       -0.690648                166             205990                    2
  340185      80D65C9A0        0.096482                103             177662                    0
  661527      81A2C5421        0.362472                124             224926                    2
  549989      815C37620        1.862333                268             224929                    2
  194221      8079D5C20       -0.617338                275             191917                    0
  338685      80D5656A0        0.094083                103             177179                    2
  683140      81AFEE120       -0.851570                218              86553                    2
  331852      80D11E6A0       -0.896273                 42             146500                    3
  274949      80ACFF9A0       -0.985871                270             170505                    3
  227785      808F20BA0       -0.799115                266             162920                    0
   96406      803C93A20       -0.828364                270             153967                    3
  512890      81444B920       -0.777490                269             124374                    2
  278155      80AEFD9A0       -0.042021                228             119419                    3
  274636      80ACC96A0       -0.842143                269             111486                    2
  491698      8136BCCA0       -0.936267                228             106776                    2
  572012      816A5C5A0       -0.521634                288              80786                    3
  310286      80C345B20       -0.873584                 48              44420                    3
  317648      80C8139A0       -0.893367                318              41809                    0
   86146      80363FBA0       -0.806993                 65              20278                    2
  560095      8162C9A20       -0.809558                292              18421                    2
  464617      812534630        1.667921                 60             150559                    3
  104432      80417FB30        1.486296                269             130081                    3
  634573      81924FBB0        1.498502                113             151724                    2
  333990      80D276030        1.683646                103             179536                    3
  411042      810318030       -0.959846                 14             205139                    2
   61948      802712730       -0.860687                 30             202999                    3
  570713      816992730       -0.502867                268             204465                    2
  334064      80D27F7B0       -0.985966                423             177433                    2
  279668      80AFFFBB0       -0.985903                275             170247                    0
   62307      80274AE30       -0.972394                269              92287                    3
  651862      819CF6A30       -0.886052                476             112239                    3
  583240      8171B4A30        0.952346                 55             222593                    0
  327889      80CE89830        1.678944                 67             169886                    3
  544627      8158B40B0        0.269149                268             206455                    3
  496824      8139FFAB0       -0.985919                103             199298                    2
  538427      8154CE6B0       -0.615710                275             191953                    2
  435027      81125D630       -0.619530                275             191407                    2
  468269      81277F830       -0.985895                166              86174                    3
  625470      818C57140        0.780727                262             217747                    3
  691105      81B4C5641        1.988891                124              66216                    2
  413935      8104E9140        1.556849                221             180295                    3
  487924      813446FC0        1.012917                 84             198906                    0
  493197      8137B2440       -0.608571                454             171918                    2
  682724      81AFAC541        1.182066                124             224926                    2
  183258      8072FD640       -0.985482                266             159674                    2
  117832      8049E6CC0       -0.849354                113             137218                    0
   94518      803B6A840       -0.980558                113             146677                    0
  330952      80D08AEC0       -0.110367                113             144951                    0
  596291      8179E39C0       -0.718523                218             128392                    2
   54892      802296640       -0.796661                218              97418                    0
  509558      8142231C0        0.045782                194              66283                    2
  293652      80B8D21C0       -0.844446                176              51564                    0
  553276      815E4FDD0        1.856416                268             204889                    0
  692734      81B5BF250        1.990353                195             147662                    0
  206479      8081A7750        1.573654                270             158272                    2
  127768      80502F0D0        1.506523                113             136272                    0
  658863      81A11F251        1.152730                124              69793                    2
  143197      8059FF9D0       -0.985871                270             152864                    3
   59279      802557950       -0.878127                218             116760                    0
  635488      8192DC0D0       -0.879532                113             142750                    3
  711654      81C152A51        1.204954                124               7604                    0
  641307      819679ED1       -0.984330                396             224926                    2
  620645      8189467D0        0.329680                396             224930                    2
  558428      8161B50D0        0.268895                268             224929                    2
  556644      81608A2D0        1.873713                268             204362                    0
  488459      81349CCD0        0.991078                 84             192228                    0
  344998      80D9700D0        0.026198                113             138219                    2
  102817      8040852D0        1.484636                113             150747                    3
  172293      806C2B2D0       -0.899641                228              91336                    0
   69562      802BEE150       -0.851570                218             132178                    0
   35315      801648650       -0.972013                228             134377                    2
  711653      81C152A50        1.204954                124             224886                    0
  641306      819679ED0       -0.984330                396             218569                    2
  537184      8153FCF50       -0.529678                268             205074                    3
  356682      80E0DC9D0        0.096482                103             179820                    3
  691352      81B4EB050        0.873215                491             175973                    0
     375      80007FED0       -0.985855                266             152401                    2
  286550      80B4616D0       -0.848242                218             109628                    3
  267701      80A861050       -0.815753                269              92573                    0
  340274      80D66D250        0.091979                307              71063                    0
  343210      80D84E650        0.685443                180              39969                    0
  522722      814AB3E50       -0.836433                335              38114                    3
   94989      803BB22E0       -0.673716                113             150429                    0
  416555      81068C6E0        1.678094                462              96723                    3
  653788      819E1D3E0        1.673727                455             194380                    3
  107663      80438BE60       -0.728680                172             200278                    0
  378368      80EE82060       -0.694023                145              40276                    3
   33026      8014E6360       -0.719452                269             135133                    0
  655324      819F0A5E1        1.158186                124              72908                    3
  169301      806A4B8E0        1.532063                270             152395                    0
   78474      80317FF60       -0.985847                113             150894                    0
  350846      80DD1EE60        1.543523                191             176385                    0
  456234      811FF9960       -0.984354                 84             192228                    0
  174548      806D8AD60       -0.728379                228             100396                    2
  565645      816650DE0        0.717646                322             214905                    3
  480965      812FB5460        0.203893                 84             192228                    0
  430759      810FB33E0        1.765723                275             192148                    0
  329429      80CF85360        0.866592                491             176303                    0
  301779      80BDE6CE0        1.655381                386             170247                    0
  223559      808C74C60       -0.007165                266             224927                    2
  332033      80D137C60       -0.869947                462              95869                    2
  681299      81AED8960        0.325193                490             209112                    3
  586611      8173DD260        1.006858                401             153335                    2
   11782      8007A61E0       -0.898322                320             195645                    0
  125141      804E86360       -0.890230                113             147828                    3
  672944      81A9BF660       -0.676964                228             130512                    3
  428708      810E6B260       -0.005100                218             123453                    0
   72799      802DE9E60       -0.785098                218             102361                    2
  216310      808800B60       -0.888578                339              93988                    3
  348869      80DBDE9F0        1.494722                 78             223399                    0
  698293      81B928570       -0.833717                380             195175                    2
  489017      8134F9FF0       -0.984314                481             199880                    0
  606708      818079E70       -0.984338                396             210106                    3
  124553      804E27F70        0.695497                113             146239                    2
  525098      814C29DF0        0.044448                123             111774                    0
  448661      811B11A70        0.766067                462             105349                    2
  302142      80BE2A4F0       -0.931820                462             110505                    2
   68771      802B6CDF0       -0.688218                339             117545                    2
  584412      817276A70       -0.886052                476             220205                    3
   57647      802451070       -0.941803                214             210008                    0
  303239      80BED56F0        0.065620                386             172716                    2
  266761      80A7C14F0        0.818902                266             169201                    2
  444787      8118A1FF0       -0.831835                461             113099                    3
  200657      807DEAEF0       -0.915460                228             112884                    3
  101214      803F83170       -0.856906                 40              33284                    2
  691096      81B4C5101        1.988883                124              57993                    3
  520786      81497B400        1.845092                381             125102                    0
  264579      80A664500        1.623249                188             129192                    3
  563427      8164E7000        1.882640                228             123963                    3
  122423      804CC7880       -0.971663                186             169824                    0
  461292      812326500        0.988425                 84             192228                    0
  249947      809CFB080        0.804091                266             224927                    2
  450072      811BFF480       -0.985958                294             149225                    2
  276845      80AE2FE00       -0.932996                462             100313                    3
  151886      805F62100       -0.848512                218             117545                    2
  560460      816302700       -0.043387                203             217274                    2
   26414      8010C9A80       -0.809558                292             216545                    2
  510899      8142FFB80       -0.985911                270             199601                    3
  328773      80CF1F200       -0.018307                270             158446                    2
  517860      814797D80        1.024885                218             134295                    0
  492748      813764800       -0.035683                228             120612                    2
  223929      808CB1B80       -0.966088                228              87970                    2
  498958      813B57180        0.780727                262              59354                    2
  587644      817477680       -0.105673                164              40609                    2
  466288      812636F00       -0.837171                261              37347                    0
  185641      807477090       -0.756286                 80             212567                    0
  478285      812DFDB90        1.486804                269             129027                    2
  512574      814419B90       -0.699757                269             112608                    0
  652861      819D93B90        1.871561                268             224929                    2
  179412      80709C010       -0.050042                238              98352                    3
  555078      815F73C10        1.066555                268             204125                    0
  404405      80FEDBB90       -0.651472                 18             189372                    2
  514360      81453AA90       -0.903333                279             154464                    2
  298155      80BBA2690       -0.832240                228             120292                    0
   74112      802ECA610       -0.809868                 89             156149                    3
  164396      806742790       -0.937943                376              88852                    3
  489058      8134FFA10       -0.985919                103             189554                    0
  245777      809A53010        1.594961                266             159305                    2
  518500      8147FCD90       -0.919995                297             211383                    0
  325286      80CCE9090        1.621891                301             212770                    0
  291895      80B7BD310        0.722252                  9             184130                    2
   65743      802982490       -0.889134                276              97888                    2
  558340      8161A7E90       -0.508093                268             208962                    2
  490674      81360E890       -0.566829                481             200479                    0
   92384      803A25290       -0.865595                113             138344                    3
  414927      810594390       -0.926317                228             109850                    3
  104146      804157110       -0.943304                228             102871                    2
   70128      802C4AE90       -0.972394                269              89230                    3
   58874      802518110       -0.894764                452              12140                    0
  118993      804A9E5A0        1.478386                 99             211725                    0
  282194      80B1A4220        1.639403                228             115593                    2
   21865      800DFF8A0       -0.985895                166             149345                    2

In [9]:
caminho = "/content/drive/MyDrive/Aula_llm/Trabalho final/Dados/IBM/"
df_accounts.to_csv(
    caminho + 'dados_account_tratada.csv',
    index=False
)